services:
  db:
    image: postgres:16
    container_name: flyrank-postgres
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: flyrank-api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tasks
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: